apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-dev
  namespace: argocd
  labels:
    env: dev
  spec:
    project: hello
    source:
      repoURL: https://github.com/bekarys2003/GitOps_Hello-World_Platform.git
      targetRevision: main
      path: charts/hello
      helm:
        valueFiles:
          - ../../envs/dev/values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-stage
  namespace: argocd
  labels:
    env: stage
  spec:
    project: hello
    source:
      repoURL: https://github.com/bekarys2003/GitOps_Hello-World_Platform.git
      targetRevision: main
      path: charts/hello
      helm:
        valueFiles:
          - ../../envs/stage/values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: stage
    syncPolicy:
      automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-prod
  namespace: argocd
  labels:
    env: prod
spec:
  project: hello
  source:
    repoURL: https://github.com/bekarys2003/GitOps_Hello-World_Platform.git
    path: charts/hello
    helm:
      valueFiles:
        - ../../envs/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}