name: Bump dev tag
on:
  push:
    branches: [ main ]


permissions:
  contents: write


jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set image tag to current SHA
        run: |
          yq -i '.image.tag = "'${{ github.sha }}'"' envs/dev/values.yaml
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add envs/dev/values.yaml
          git commit -m "chore(dev): bump image tag to ${{ github.sha }}"
          git push